// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePostgresSslUrl } from "./lib/database/normalize-postgres-ssl-url";

const connectionString = process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Keep Prisma CLI migrations on the same explicit certificate-verification
    // behavior as the application's PrismaPg connection pool.
    url: connectionString
      ? normalizePostgresSslUrl(connectionString)
      : undefined,
  },
});
